CREATE TYPE gender_enum AS ENUM ('M', 'F', 'O');
CREATE TYPE role_enum AS ENUM ('ROLE_ADMIN', 'ROLE_LIBRARIAN', 'ROLE_MEMBER');
CREATE TYPE user_status_enum AS ENUM ('ACTIVE', 'INACTIVE', 'BANNED');
CREATE TYPE copy_status_enum AS ENUM ('AVAILABLE', 'BORROWED', 'LOST', 'DAMAGED', 'MAINTENANCE');
CREATE TYPE loan_status_enum AS ENUM ('BORROWED', 'RETURNED', 'OVERDUE', 'LOST');
CREATE TYPE fine_status_enum AS ENUM ('UNPAID', 'PAID', 'WAIVED');