spring.datasource.url=jdbc:postgresql://localhost:5432/libero
spring.datasource.username=postgres
spring.datasource.password=minh0910
spring.jpa.show-sql=true

# Logging configuration for development
logging.level.com.libero=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO